name: Deploy Qgoda Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build & Deploy with Qgoda
        uses: gflohr/qgoda-action@main
        with:
          qgoda_version: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}

